theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/home"
alias = "/home"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 5
format = "{barchart}"

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "net"
device = "enp3s0"
interval = 15
use_bits = false

[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
