image: nixos/unstable
sources:
- https://git.sr.ht/~eduardo_quiros/dotfiles
environment:
    NIX_CONFIG: "experimental-features = nix-command flakes"
tasks:
- flake-check: |
    cd dotfiles
    nix flake check --all-systems
