# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[devshell]
packages = [
"nixpkgs-fmt",
"nodePackages.bash-language-server",
"rnix-lsp",
"shfmt",
"stylua",
]
