# https://numtide.github.io/devshell
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"

[[commands]]
package = "treefmt"
help = "Format code with treefmt"

[devshell]
packages = ["alejandra", "shfmt", "stylua"]
