# One CLI to format the code tree - https://github.com/numtide/treefmt

[formatter.nix]
# Formatter to run
command = "alejandra"
# Command-line arguments for the command
options = []
# Glob pattern of files to include
includes = [ "*.nix" ]
# Glob patterns of files to exclude
excludes = []

[formatter.shell]
command = "shfmt"
options = [
  "--indent",
  "0",  # indent with tabs
  "--simplify",  # simplify the code
  "--write",  # write back to the file
]
includes = ["*.sh"]

[formatter.lua]
command = "stylua"
includes = [ "*.lua" ]
