#!/bin/sh
#LINES=30
case "$1" in
	#*.pdf) pdftotext "$1";;
    *.md) glow -s dark "$1";;
    *.org) bat "$1";;
    #*.png | *.jpg | *jpeg) kitty +kitten icat "$1" ;;
    *.png | *.jpg | *jpeg) mediainfo "$1" ;;
	*.mkv | *.mp4 | *.webm) mediainfo "$1";;
    *) highlight "$1" -O ansi --force;;
esac
