# _    _ _   _                           __
#| | _(_) |_| |_ _   _   ___ ___  _ __  / _|
#| |/ / | __| __| | | | / __/ _ \| '_ \| |_
#|   <| | |_| |_| |_| || (_| (_) | | | |  _|
#|_|\_\_|\__|\__|\__, (_)___\___/|_| |_|_|
#                |___/

# Fonts
font_family Fira Code
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.0
# Fonts

active_border_color #e2b0ff
active_tab_background #f8f8f2
active_tab_foreground #44475a
background #282a36
background_opacity 0.75
color0 #21222c
color1 #ff5555
color10 #69ff94
color11 #ffffa5
color12 #d6acff
color13 #ff92df
color14 #a4ffff
color15 #ffffff
color2 #50fa7b
color3 #f1fa8c
color4 #bd93f9
color5 #ff79c6
color6 #8be9fd
color7 #f8f8f2
color8 #6272a4
color9 #ff6e6e
cursor #f8f8f2
cursor_stop_blinking_after 0.2
cursor_text_color background
dim_opacity 0.75
foreground #f8f8f2
inactive_tab_background #6272a4
inactive_tab_foreground #282a36
inactive_text_alpha 0.8
selection_background #f8f8f2
selection_foreground #44475a
strip_trailing_spaces smart
tab_bar_style fade
tab_fade 0.2 0.45 0.6 0.9
tab_separator ~~
url_color #ffb86c
window_border_width 1
window_margin_width 1
window_padding_width 5





