# Fonts
font_family      Fira Code
#font_family NerdFonts
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# Fonts

# Cursor
cursor_stop_blinking_after 0.2
# Cursor

# Window
window_border_width 1
window_margin_width 1
window_padding_width 5
active_border_color #e2b0ff
inactive_text_alpha 0.8
# Window

# Tab
tab_bar_style fade
tab_separator "~~"
tab_fade 0.2 0.45 0.6 0.9

active_tab_foreground   #FFF
active_tab_background   #FFA939
active_tab_font_style   bold
inactive_tab_foreground #F9F3EE
inactive_tab_background #009CC6
inactive_tab_font_style normal
# Tab

# Color scheme
background_opacity 0.75
dim_opacity 0.75
selection_background #F9F3EE
# Color scheme

# Copy
strip_trailing_spaces smart
# Copy

# Mouse
mouse_hide_wait 1
# Mouse

# Mappings
