#!/bin/sh
borg create --progress \
	~/Games/ ~/Documents/ ~/Pictures/ ~/Videos/ ~/Music/ ~/Templates/ ~/Downloads/\
	/run/media/eduardo/2e571771-81db-41a5-a0b6-d5c6d3b8bf88/borg/::\{hostname\}-\{user\}\
	--exclude "*/league-of-legends/*"\
	--exclude '*/.stfolder'\
	--compression auto,lz4
