#!/bin/sh

case "$1" in
	*.md) pandoc "$1" -o "$1.pdf" && rename ".md" "" "$1.pdf";;
	*.ms) groff -k -ms "$1" >> "$1.pdf" && rename ".ms" "" "$1.pdf";;
	*.c) gcc "$1" -o "$1";;
	*.cpp) g++ "$1" -o "$1";;
esac
