#!/bin/sh

[ -e ./.envrc ] || echo "use nix" > .envrc && direnv allow
[ -e shell.nix ] || [ -e default.nix ] ||\
	cat > default.nix <<'EOF'
with import <nixpkgs> {};
mkShell {
	nativeBuildInputs = [
		bashInteractive
	];
}
EOF

${EDITOR} default.nix
