#!/bin/sh
case "$1" in
	*mel*) _url="projektmelody";;
	*womble* | *soviet*) _url="sovietwomble";;
	*mouse*) _url="ironmouse";;
	*noble* | *lost* | *pause*) _url="lost_pause";;
	*nano* | *rick*) _url="xrayr6";;
	*momo*) _url="sickly_momo";;
	*silver*) _url="siivervale";;
	*) _url="$1";;
esac

exec streamlink -p mpv "https://twitch.tv/$_url" best & disown
