#!/bin/sh

case "$1" in
	*.mp4) exec mpv "$1" ;;
	*.pdf) exec zathura "$1";;
	*invidio.us* | *youtube.com*) exec mpv --ytdl=yes "$1"	;;
	http* | https* )
		case "$1" in
			*.jpg | *.png) curl "$1" >> "/tmp/image" && $IMG "/tmp/image" & disown ;;
			*) "$BROWSER" "$1" ;;
		esac;;
	mailto*)	exec aerc "$1" ;;
	*.html) exec "$BROWSER" "$1" ;;
	*) echo "Unhandled" ;;
esac
