#!/bin/sh

case "$1" in
	*.mp4 | *.webm | *.mkv) exec umpv "$1" & disown ;;
	*invidio.us* | *youtube.com*) exec umpv --ytdl=yes "$1" & disown	;;
	*twitch*) exec streamlink -p mpv "$1" best & disown ;;
	http* | https* )
		case "$1" in
			*.jpg | *.png) curl "$1" -o "/tmp/image" && $IMG "/tmp/image" & disown ;;
			*) "$BROWSER" "$1" ;;
		esac;;
	*.jpg | *.png) exec "$IMG" "$1" & disown ;;
	mailto*)	exec aerc "$1" ;;
	magnet*) exec stig add "$1";;
	*.pdf | *.html) exec "$BROWSER" "$1" ;;
	*)  exec /run/current-system/sw/bin/xdg-open "$1" ;;
esac
