#!/bin/sh

case "$1" in
	*.pdf) exec "$READER" "$1" ;;
	*.mp4 | *.webm | *.mkv) exec umpv "$1" & disown ;;
	*share.tube* | *peertube* ) exec umpv "$(echo $1-1080.mp4 | sed s:videos/watch:download/videos:g)";;
	*invidio* | *nettohikari* | *youtube.com*) exec umpv --ytdl=yes "$1" & disown	;;
	*twitch*) exec streamlink -p mpv "$1" best & disown ;;
	magnet* | *.torrent) exec stig add "$1"; notify-send "Torrent Added! 酪";;
	http* | https* )
		case "$1" in
			*.jpg | *.png) curl "$1" -o "/tmp/image" && $IMG "/tmp/image" & disown ;;
			*) "$BROWSER" "$1" ;;
		esac;;
	*.jpg | *.png) exec "$IMG" "$1" & disown ;;
	mailto*)	exec aerc "$1" ;;
	*.html) exec "$BROWSER" "$1" ;;
	*)  exec /run/current-system/sw/bin/xdg-open "$1" ;;
esac
