#!/bin/sh
#      _       _ _
#__  _(_)_ __ (_) |_ _ __ ___
#\ \/ / | '_ \| | __| '__/ __|
# >  <| | | | | | |_| | | (__
#/_/\_\_|_| |_|_|\__|_|  \___|

sxhkd &
picom &
udiskie &
xidlehook --timer 300 "betterlockscreen -l" "" & disown
exec awesome
