#!/bin/sh
#      _       _ _
#__  _(_)_ __ (_) |_ _ __ ___
#\ \/ / | '_ \| | __| '__/ __|
# >  <| | | | | | |_| | | (__
#/_/\_\_|_| |_|_|\__|_|  \___|

sxhkd &
picom &
redshift &
qsyncthingtray &
xrandr -r 144
xidlehook --timer 300 "slock" "" & disown
exec awesome
