autoclip: true
autoimport: true
cliptimeout: 45
exportkeys: false
mime: false
nocolor: false
nopager: false
notifications: true
path: /home/eduardo/.local/share/password-store
safecontent: false
mounts: {}
