{
  config,
  pkgs,
  ...
}: {
  home-manager.users.kiri = {
    programs.neovim = {
      enable = true;
      extraPackages = [] ++ import ./editorPackages.nix {inherit pkgs;};
      generatedConfigs.lua = ''
        -- Generated by Home Manager
        vim.opt.background = "dark"
      '';
      viAlias = true;
      vimAlias = true;
      vimdiffAlias = true;
    };
  };
}
