#!/bin/sh
#       _ _
#  __ _| (_) __ _ ___  ___  ___
# / _` | | |/ _` / __|/ _ \/ __|
#| (_| | | | (_| \__ \  __/\__ \
# \__,_|_|_|\__,_|___/\___||___/
# This is eduardo's alias file, originally inspired by Luke Smith's layout,
# which can be found here: https://github.com/LukeSmithxyz/voidrice/blob/master/.config/aliasrc
# The license, naturally, is the same as that file.

# In case nvim is present, replace vim with it
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Torify all the things!
alias aerc="torify aerc"\
	drive="torify drive"\
	git="torify git"\
	lazygit="torify lazygit"\
	mpv="torify mpv"\
	toot="torify toot"

# Shortening some commands
alias c="cd"\
	dateh="date --help | grep %"\
	g="git"\
	gcp="git commit -a; git push"\
	lg="lazygit"\
	mkdir="mkdir -pv"\
	nrebuild="sudo nixos-rebuild switch --upgrade; flatpak update -y"\
	nsp="nix-shell -p"\
	rm="rm -rvI"\
	v="$EDITOR"\
	vi="$EDITOR"

# Replacements
alias cat="bat -p"\
	find="fd"\
	grep="rg"
