#!/bin/sh
#       _ _
#  __ _| (_) __ _ ___  ___  ___
# / _` | | |/ _` / __|/ _ \/ __|
#| (_| | | | (_| \__ \  __/\__ \
# \__,_|_|_|\__,_|___/\___||___/
# This is eduardo's alias file, originally inspired by Luke Smith's layout,
# which can be found here: https://github.com/LukeSmithxyz/voidrice/blob/master/.config/aliasrc
# The license, naturally, is the same as that file.

# In case nvim is present, replace vim with it
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Torify all the things!
alias aerc="torify aerc"\
	git="torify git"\
	lazygit="torify lazygit"\
	mpv="torify mpv"

# Shortening some commands
alias c="cd"\
	dateh="date --help | grep %"\
	g="git"\
	lg="lazygit"\
	nrebuild="sudo nixos-rebuild switch --upgrade"\
	v="$EDITOR"

# Replacements
alias cat="bat -p"\
	find="fd"\
	grep="rg"
