#!/bin/sh
# This is a file dedicated to the cleanup of the $HOME directory by following
# the XDG base directory specification

# Environmental Variables
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"
export IDEA_PROPERTIES="$XDG_CONFIG_HOME/intellij-idea/idea.properties"
export IDEA_VM_OPTIONS="$XDG_CONFIG_HOME/intellij-idea/idea64.vmoptions"
export LESSHISTFILE=- # Disable less history file
export UNISON="$XDG_DATA_HOME/unison"
export XCOMPOSEFILE="$XDG_CONFIG_HOME/X11/xcompose"
export XCOMPOSECACHE="$XDG_CACHE_HOME/X11/xcompose"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

# Aliases
alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"
alias startx="startx '$XDG_CONFIG_HOME/x11/xinitrc'"
