[battery]
charging_symbol = ""
discharging_symbol = ""
full_symbol = ""

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hostname]
ssh_only = false

[nix_shell]
use_name = true
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[username]
show_always = true
